pipeline {
  agent { label 'maven' }
  stages {  
    stage ('GIT-CLONE') {	
	  steps{
	    git branch: 'demo', changelog: false, credentialsId: 'github', poll: false, url: 'https://github.com/Vimala-Daniel/JenkinsWar.git'		  
	  }	
	}
    stage ('MAVEN-BUILD') {	
	  steps{
	   sh "/opt/maven/bin/mvn clean install"	  	  
	  }	
	}	 
    stage ('DEPLOY-TOMCAT') {
	  steps{
	   deploy adapters: [tomcat9(credentialsId: 'tomcat', path: '', url: 'http://52.87.241.68:8080/')], contextPath: 'pipeline-scm', war: 'target/*.war'
	   sh """
	   echo "Pipeline Deploy Test"
	   """
      } 
    }
  }
}
