pipeline {
  agent {
  label 'jenkinsmaster'
   }
  parameters {
  string description: 'enter ami id', name: 'ami'
  string description: 'enter Instance count', name: 'Instancecount'
  string description: 'enter instance type', name: 'instancetype'
  string description: 'enter keypair', name: 'keypair'
  string description: 'enter sgid', name: 'sgid'
  string description: 'enter region', name: 'region'
   }
    stages {  
    stage ('Instance Creation - Dynamic') {	
	  steps{
	    sh """
            aws ec2 run-instances --image-id $ami --count $Instancecount --instance-type $instancetype --key-name $keypair --security-group-ids $sgid --region $region
	       """      
      } 
    }
  }
}
