pipeline {
  agent {
  label 'jenkinsmaster'
   }
  parameters {
  choice choices: ['us-east-1', 'us-west-1', 'ap-south-1'], description: 'choose region', name: 'region'
  string description: 'enter bucket name', name: 'bucket-name'
  choice choices: ['private', 'public-read', 'public-read-write', 'aws-exec-read', 'authenticated-read', 'log-delivery-write'], description: 'choose acl', name: 'acl'
     }
    stages {  
    stage ('Bucket-creation') {	
	  steps{
	    sh """
           cd $WORKSPACE/demo/Terraform/s3bucket/variables3-fullform/
           /usr/local/bin/terraform init
           /usr/local/bin/terraform apply -var "region=$region" -var "bucket_name=$bucket_name" -var "acl=$acl" --auto-approve	       """      
         """
      } 
    }
  }
}
