pipeline {
  agent { label 'maven' }
  parameters {
  string description: 'Enter the branch name', name: 'branchname'
  }
   stages {  
    stage ('GIT-CLONE') {	
	  steps{
	    git branch: '$branchname', changelog: false, credentialsId: 'github', poll: false, url: 'https://github.com/Vimala-Daniel/JenkinsWar.git'		  
	  }	
	}
 
   }
}   
