pipeline {
  agent {
  label 'slavenode1-maven'
   }
  stages {  
    stage ('GIT-CLONE') {	
	  steps{
	    git branch: 'demo', changelog: false, credentialsId: 'github', poll: false, url: 'https://github.com/Vimala-Daniel/JenkinsWar.git'		  
	  }	
	}
    stage ('MAVEN-BUILD') {	
	  steps{
	   sh "/opt/maven/bin/mvn clean deploy"	  	  
	  }	
	}	 
    stage ('NEXUS-TOMCAT-DEPLOY') {
	  steps {
	   deploy adapters: [tomcat9(path: '', url: 'http://54.197.44.32:8080/')], contextPath: 'nexuspipe', war: 'target/*.war'
	   }  
    }
  }
}
