pipeline {
  agent { label 'maven' }
  stages {  
    stage ('GIT-CLONE') {	
	  steps{
	    checkout([$class: 'GitSCM', branches: [[name: 'demo']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Vimala-Daniel/JenkinsWar.git']]])
	  }	
	}
    stage ('MAVEN-BUILD') {	
	  steps{
	   sh "/opt/maven/bin/mvn clean install"	  	  
	  }	
	}	 
  }
}
